### PR TITLE
[Scrum-48] user-account-login

### PR DESCRIPTION
**Pull request by kylasim**

### CODE REVIEW

**Comment by kylasim** [comment]
login screen done, should look like this
Screenshot 2024-01-23 123833

**Comment by jeremygmc** [comment]
1. install dependencies
in terminal (vscode):
`cd app`
`npm install`
2. deploy app
in terminal (vscode):
`npm run build`

**Comment by jeremygmc** [comment]
@kylasim doublecheck font size is 14px and increase horizontal padding to fit figma please

current:
image

figma:
image

**Comment by kylasim** [comment]
Fixes done:
Screenshot 2024-01-26 234248

**Review by gohgicci — APPROVED** [review]

**Review by KeithLaww — APPROVED** [review]
Reviewed

**Pull request merged**
